site_name: ReadMyDocs
nav:
  - Home: index.md
  - Docker: docker.md
  - GitHub: gitnotes.md
  - Linux Commands: commands.md
  - OpenVPN: openvpn.md
  - Samba: samba.md
  - WebAccess/DMP: webaccessdmp.md
  - About: about.md
theme: readthedocs
extra_css: [extra.css]

