site_name: ReadMyDocs
nav:
  - Home: index.md
  - Cool Resources: resources.md
  - Docker: docker.md
  - GitHub: gitnotes.md
  - Linux Commands: commands.md
  - Java Script: javascript.md
  - Node-RED: nodered.md
  - OpenSSH: openSSH.md
  - OpenVPN: openvpn.md
  - Samba: samba.md
  - WebAccess/DMP: webaccessdmp.md
  - WireGuard: wireguard.md
  - About: about.md
theme: readthedocs
extra_css: [extra.css]


